---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:1.0.0-451

dependencies:
  galaxy:
    collections:
      - infra.controller_configuration
      - ansible.controller
      - ansible.windows

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: files
    dest: configs

additional_build_steps:
  prepend_base:
    - RUN pip3 install --upgrade pip setuptools
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG AH_TOKEN
  append_final: |
    LABEL quay.expires-after="45d"