---
version: 1

ansible_config: './ansible.cfg'

dependencies:
  galaxy: requirements.yml
  #python: requirements.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append: |
    RUN git clone https://github.com/kubernetes-incubator/external-storage.git kubernetes-incubator
    LABEL quay.expires-after="45d"