---
version: 3

images:
  base_image:
    name: ansible-automation-platform/ee-minimal-rhel8:2.15.4-4

dependencies:
  # ansible_core:
  #   package_pip: ansible-core==2.15.4
  galaxy:
    collections:
      - 'networktocode.nautobot'
      - netbox.netbox
      - community.general
  python:
    - pynautobot
    - pytz
    - pynetbox
    - jmespath

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: files
    dest: configs

additional_build_steps:
  prepend_base:
    - RUN pip3 install --upgrade pip setuptools
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG AH_TOKEN
  # prepend_base:
  #   - COPY _build/configs/cert.pem /etc/pki/ca-trust/source/anchors/cert.pem
  #   - RUN update-ca-trust
  append_final: |
    LABEL quay.expires-after="45d"