---
collections:
  - ansible.utils
  - community.general
  - redhat.rhel_system_roles
  - redhat.insights
  - ansible.posix
roles:
  - linux-system-roles.firewall
  - redhatinsights.insights-client
  - redhatofficial.rhel8_stig
  - geerlingguy.nfs
