---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/de-minimal-rhel9:latest

dependencies:
  python_interpreter:
    python_path: /usr/bin/python3.11
  galaxy:
    collections:
      - name: ansible.eda
      - name: servicenow.itsm
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.11-devel [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_galaxy:
    # This setups up the various collection repos needed during the build process.
    # The following need to be provided to ansible-builder as using the --build-arg option:
    #   ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_TOKEN
    #   ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_VALIDATED
    - ENV ANSIBLE_GALAXY_SERVER_LIST=rh_certified_repo,rh_certified_repo_validated,release_galaxy
    - ENV ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_URL=https://console.redhat.com/api/automation-hub/content/published/
    - ENV ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ARG ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_VALIDATED_URL=https://console.redhat.com/api/automation-hub/content/validated/
    - ENV ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_VALIDATED_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    - ARG ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_VALIDATED_TOKEN
    - ENV ANSIBLE_GALAXY_SERVER_RELEASE_GALAXY_URL=https://galaxy.ansible.com
    - ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS="-f"
  append_final: |
    LABEL quay.expires-after="45d"
