---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:1.0.0-913

dependencies:
  galaxy:
    collections:
      - ansible.platform
      - ansible.hub
      - ansible.controller
      - ansible.eda
      - ansible.utils
      - infra.aap_configuration
      - brianaddicks.rh_console_imagebuilder
      - community.general
      - cloud.common
      - vmware.vmware_rest
      - community.vmware
      - redhat.rhel_system_roles
      - redhat.insights
      - ansible.posix
    roles:
      - linux-system-roles.firewall
      - linux-system-roles.storage
      - linux-system-roles.selinux
      - redhatinsights.insights-client
      - redhatofficial.rhel8_stig
      - geerlingguy.nfs
  python:
    - jmespath
    - aiohttp
    - pyVmomi>=6.7
    - git+https://github.com/vmware/vsphere-automation-sdk-python.git ; python_version >= '2.7' # Python 2.6 is not supported
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.11-devel [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: files
    dest: configs

additional_build_steps:
  prepend_base:
    - COPY _build/configs/vcenterCA.crt /usr/share/pki/ca-trust-source/anchors
    - RUN update-ca-trust
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_TOKEN
  append_final: |
    LABEL quay.expires-after="45d"
