# Workflow name
name: Ansible Controller EE Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'ansible-controller-ee/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  brianaddicks/ansible-ee/.github/workflows/deploy-multiarch.yml@main
    with:
      EE_FOLDER_NAME: 'ansible-controller-ee'
      EE_IMAGE_TAG: 'latest'
    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}