# Workflow name
name: Home Lab EE Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'home-lab-ee/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  brianaddicks/ansible-ee/.github/workflows/deploy-multiarch6.yml@main
    with:
      EE_FOLDER_NAME: 'home-lab-ee'
      EE_IMAGE_TAG: 'latest'
      CA: ${{ vars.VCENTER_CA }}

    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_TOKEN: ${{ secrets.ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_TOKEN }}
      ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_VALIDATED_TOKEN: ${{ secrets.ANSIBLE_GALAXY_SERVER_RH_CERTIFIED_REPO_VALIDATED_TOKEN }}