# Workflow name
name: vsphere EE Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'vsphere-ee/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  brianaddicks/ansible-ee/.github/workflows/deploy-multiarch.yml@main
    with:
      EE_FOLDER_NAME: 'vsphere-ee'
      EE_IMAGE_TAG: 'latest'
      CA: |
        -----BEGIN CERTIFICATE-----
        MIIELTCCAxWgAwIBAgIJAMjK8QNywJodMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYD
        VQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZ
        FgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExIzAhBgNV
        BAoMGmFkZC1hY3ctdmNzLTAwMS5hZGRpY2tzLnVzMRswGQYDVQQLDBJWTXdhcmUg
        RW5naW5lZXJpbmcwHhcNMjIwNDI1MTg1OTIyWhcNMzIwNDIyMTg1OTIyWjCBoTEL
        MAkGA1UEAwwCQ0ExFzAVBgoJkiaJk/IsZAEZFgd2c3BoZXJlMRUwEwYKCZImiZPy
        LGQBGRYFbG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMSMw
        IQYDVQQKDBphZGQtYWN3LXZjcy0wMDEuYWRkaWNrcy51czEbMBkGA1UECwwSVk13
        YXJlIEVuZ2luZWVyaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        keHwleApC6Z+C0i8+usFho2TQO2HIPW6BCMNWwZv8X2hrJPpphSKraOLhyOwjCLM
        F9hiCeocZskPuYVG+FYNUs3eLiQvvDu3r1ypyhzPkv25J+qbOd6Y7nYJ5aIpoaF1
        GxTPk5lSw5V6o1HbPpFblSScBoacQQxM7Sq+BN+7+AnoX8ydZrN4SCrMwlXr7Ljb
        NSsULMIGXkadn8is/S6adOJrfqR/qZa0S2Wcp0BWcQBFM1cuWWu5VaVbUwkqCUjo
        LlTI+G5m0hoK/0Yus4xqwhlQslEHWM5kPGeOEoErPiSyKrPGZREAbo8L2kaiKrP/
        AebC8kENO+3CET5oDkieCwIDAQABo2YwZDAdBgNVHQ4EFgQUKQs0bBPbvNQL/Auj
        MtLhU0CFuMYwHwYDVR0RBBgwFoEOZW1haWxAYWNtZS5jb22HBH8AAAEwDgYDVR0P
        AQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwDQYJKoZIhvcNAQELBQADggEB
        AF0zcIrelQOxz+3W1s0ud2crnI9IXBjD3WjWqmyMzolcAZfg3koKse4Oqn1Lcdyh
        MuO2miO8sl1wcNQVkqhXmxgIJ2RRe2ENCfSiIPMfeQy8Hbgupikb/EiHn1IhDwXL
        z9tqiGE26zFDDWitW9zzzHeJw1s5D5SOj7RnQrjOx/BJtVAvk9hbuyPZ6EmTeql/
        P/Js0UYstoDdY3JQ04nEyi+CLriZFdyRr9JGmdKMYrfVCJR3C+1Bjp9v8Kdih2qm
        rjDFXpjHbwqXRzC2Yx2DfElJU4Fyb87u2GAwjw0KsDjwLLw6TNgooUNnBykNz+CQ
        yIRajFKfdYIHItlZcvaCjnM=
        -----END CERTIFICATE-----
    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}