# Workflow name
name: vsphere EE Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'vsphere-ee/**'

  # Schedule workflow run at 00:00 on Sunday
  # schedule:
  #   - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  brianaddicks/ansible-ee/.github/workflows/deploy-multiarch3.yml@main
    with:
      EE_FOLDER_NAME: 'vsphere-ee'
      EE_IMAGE_TAG: 'latest'
      CA: |
        -----BEGIN CERTIFICATE-----
        MIIELTCCAxWgAwIBAgIJAM04tTKQicZNMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYD
        VQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZ
        FgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExIzAhBgNV
        BAoMGmFkZC1hY3ctdmNzLTAwMS5hZGRpY2tzLnVzMRswGQYDVQQLDBJWTXdhcmUg
        RW5naW5lZXJpbmcwHhcNMjMwMjI2MTYyMjA1WhcNMzMwMjIzMTYyMjA1WjCBoTEL
        MAkGA1UEAwwCQ0ExFzAVBgoJkiaJk/IsZAEZFgd2c3BoZXJlMRUwEwYKCZImiZPy
        LGQBGRYFbG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMSMw
        IQYDVQQKDBphZGQtYWN3LXZjcy0wMDEuYWRkaWNrcy51czEbMBkGA1UECwwSVk13
        YXJlIEVuZ2luZWVyaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
        uhAsa70UiuIs0pw0sm1Wh79T8SyTqOwfh8yKhesRc8mmliOydzm1AiePtNYWXMU1
        SWakF0hPCGZniIY+bVNlogsQG3I89jqNkhXEJSmKcZfprD55kPjh5JqSGlE1FXb4
        b914xks7X6ejo5Jdp6eybgYjL6pW1ppnkuqZ7ETodhreV5zSyyu2cWKCDjEjnJtX
        1jfSRnxAGwARYTm9z3Eaz5jPRP+Rl8TJ98pa+k7OZK5/9T7jWZRvZNbXPYtSSFol
        maySY5e04SKaTI1bvRDuF7ac9zh7reArvdON32hwabCYBUBB8gUSM9Rr9NfU6kzG
        6qpUtgMi2Qas63xYdi6ztwIDAQABo2YwZDAdBgNVHQ4EFgQUoVQxMaf5RP9vyqOY
        5DRkYBFiGk8wHwYDVR0RBBgwFoEOZW1haWxAYWNtZS5jb22HBH8AAAEwDgYDVR0P
        AQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwDQYJKoZIhvcNAQELBQADggEB
        AKZ8xJTF8kTFt18b97olyh/fY/fYWdHIg/mHd7POoLzWlaGCKHv9y+1oPcJHnQLm
        1aSbAi3eSeZbMkJyWMsHvz9oZ3TRntUzpVQAOb70ATNh4ktGOOoohHHr6FudMqJL
        oWdc62wT6ARV7mxDw+PuBvKqth2rYX04Utso+zF8m6Y6eDOLQgAyka79ezbNhai6
        rfUUyN8F3vd2p4CBlIJyXLzqaHLCeADYaZyJI1lbWXQNqMKMV/hRG6k6tDaFI1fP
        2OWO+LRRVvPGHUXFoedRgb8+I1yVWpZIDaq7F+H26U9Rsnjo0BgsZU49ZIZTK3Ay
        DLqtLrCVvZyfSigfLh43A2k=
        -----END CERTIFICATE-----

    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}